# Generated by Django 4.0.1 on 2022-01-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clasificacioncaso',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('casoasig', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='eess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('iddiresa', models.CharField(max_length=3)),
                ('diresa', models.CharField(max_length=100)),
                ('idredes', models.CharField(max_length=3)),
                ('redes', models.CharField(max_length=100)),
                ('idmicrored', models.CharField(max_length=3)),
                ('microred', models.CharField(max_length=100)),
                ('ideess', models.CharField(max_length=10)),
                ('eess', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='perllenaficha',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('perllenafichasig', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='resultado',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('resutaldoasig', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='resultadodesc',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('resutaldodescasig', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoCaso',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('tcasoasig', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoDocumento',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('documento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrueba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipovacuna',
            fields=[
                ('idv', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipovia',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('viaasig', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndocumento', models.CharField(max_length=20)),
                ('apenombres', models.CharField(default='', max_length=200)),
                ('fvacuna', models.DateField()),
                ('ndosis', models.IntegerField()),
                ('idfabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netlabv2.tipovacuna')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteNetLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndocumento', models.CharField(max_length=20)),
                ('apePaterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apeMaterno', models.CharField(blank=True, max_length=100, null=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('codOrden', models.CharField(blank=True, max_length=20, null=True)),
                ('fobtencion', models.DateTimeField(blank=True, null=True)),
                ('enfermedad', models.CharField(blank=True, max_length=200, null=True)),
                ('componente', models.CharField(blank=True, max_length=200, null=True)),
                ('resultado', models.CharField(blank=True, max_length=200, null=True)),
                ('fpublicacionr', models.DateTimeField(blank=True, null=True)),
                ('eessorigen', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('revisado', models.BooleanField(default=False)),
                ('error', models.CharField(default='', max_length=100)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('deleteAt', models.BooleanField(default=False)),
                ('tdocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netlabv2.tipodocumento')),
                ('tprueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netlabv2.tipoprueba')),
            ],
        ),
        migrations.CreateModel(
            name='NotiCovid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fnotificacion', models.DateField(null=True)),
                ('ndocumento', models.CharField(max_length=20)),
                ('apeynombres', models.CharField(max_length=200)),
                ('ncelular', models.CharField(max_length=20)),
                ('peso', models.CharField(max_length=3)),
                ('talla', models.CharField(max_length=3)),
                ('npuerta', models.CharField(max_length=20)),
                ('nombrevia', models.CharField(max_length=200)),
                ('finiciosintomas', models.DateField(blank=True, null=True)),
                ('finiciosaislamiento', models.DateField(blank=True, null=True)),
                ('sintomas', models.JSONField(blank=True, null=True)),
                ('contactodir', models.JSONField(blank=True, null=True)),
                ('vacuna1_fecha', models.DateField(blank=True, null=True)),
                ('vacuna2_fecha', models.DateField(blank=True, null=True)),
                ('vacuna3_fecha', models.DateField(blank=True, null=True)),
                ('ftmuestra', models.DateField(blank=True, null=True)),
                ('fresultado', models.DateField(blank=True, null=True)),
                ('createAt', models.DateField(auto_now_add=True)),
                ('UpdateAt', models.DateField(auto_now=True)),
                ('deleteAt', models.BooleanField(default=False)),
                ('classcaso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netlabv2.clasificacioncaso')),
                ('eess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netlabv2.eess')),
                ('perllenaficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netlabv2.perllenaficha')),
                ('resultadodesc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netlabv2.resultadodesc')),
                ('tcaso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netlabv2.tipocaso')),
                ('tdocumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netlabv2.tipodocumento')),
                ('tmuestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netlabv2.resultado')),
                ('tprueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netlabv2.tipoprueba')),
                ('tvia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netlabv2.tipovia')),
                ('vacuna1_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacuna1_id', to='netlabv2.tipovacuna')),
                ('vacuna2_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacuna2_id', to='netlabv2.tipovacuna')),
                ('vacuna3_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacuna3_id', to='netlabv2.tipovacuna')),
            ],
        ),
    ]
