# Generated by Django 4.0.1 on 2022-02-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netlabv2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='negativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=50)),
                ('residactual', models.CharField(max_length=200)),
                ('ftomamuestra', models.DateField(blank=True, null=True)),
                ('ndocumento', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('microred', models.CharField(max_length=200)),
                ('eess', models.CharField(max_length=200)),
                ('vacccovid', models.CharField(max_length=4)),
                ('f1sosis', models.DateField(blank=True, null=True)),
                ('f2dosis', models.DateField(blank=True, null=True)),
                ('f3dosis', models.DateField(blank=True, null=True)),
                ('tvacuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vacunasf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndocumento', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=50)),
                ('fnacimeinto', models.DateField(blank=True, null=True)),
                ('fvacuna', models.DateField(blank=True, null=True)),
                ('ndosis', models.IntegerField()),
                ('vacuna', models.CharField(max_length=50)),
            ],
        ),
    ]
