# Generated by Django 4.0.1 on 2022-02-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netlabv2', '0002_negativos_vacunasf'),
    ]

    operations = [
        migrations.AddField(
            model_name='negativos',
            name='createAt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
